version: "3.4"
services:
    rasa:
        image: rasa_thue_chatbot:latest
        build: "./"
        restart: always
        volumes:
            - ./actions:/app/actions
            - ./data:/app/data
            - ./models:/app/models
        command: bash -c "rm -rf .rasa/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
        working_dir: /app
        ports:
            - "5005:5005"
        networks:
            - all

    rasa-actions:
        image: rasa_thue_chatbot:latest
        build: "./"
        restart: always
        volumes:
            - ./actions:/app/actions
            - ./utils:/app/utils
        command: bash -c "rasa run actions"
        working_dir: /app
        ports:
            - "5055:5055"
        networks:
            - all

networks:
    all:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"
